[features]
seeds = false
skip-lint = false
[programs.devnet]
dapp_anchor = "3SdDNaDr95nakWywg6ArYrDD6GPxi41WhztxYqrBHJJh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
